version: '{build}'
image: Visual Studio 2017
build_script:
- ps: ./Build.ps1 -majorMinor "3.1" -patch "$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: kWjkVgz/CQ1uUURl33OhzTbq/MB35u24/uLXntDcxoXDJD1lXjozxqeNiupqxG2E
  on:
    branch: master
    
